version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "setup-android-signing"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "setup-firebase-cli"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "setup-flutter"
    schedule:
      interval: "daily"
