name: Setup Flutter
description: Setup Flutter SDK

runs:
  using: "composite"
  steps:
    - name: PATH
      shell: bash
      run: |
        echo "$HOME/fvm/versions/beta/bin" >> $GITHUB_PATH
        echo "$HOME/fvm/versions/stable/bin" >> $GITHUB_PATH
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

    - name: Env
      shell: bash
      run: |
        echo "FVM_VERSION=@3.0.0-beta.5" >> $GITHUB_ENV
        echo "FLUTTERFIRE_VERSION=0.3.0-dev.18" >> $GITHUB_ENV

    - name: Setup Homebrew
      shell: bash
      if: runner.os == 'Linux'
      run: |
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

    - name: Flutter Cache
      uses: actions/cache@v3
      if: runner.os == 'Linux'
      with:
        path: "/home/runner/fvm/versions"
        key: ${{ runner.os }}-flutter

    - name: Homebrew Cache
      uses: actions/cache@v3
      if: runner.os == 'Linux'
      with:
        path: "/home/linuxbrew/.linuxbrew/Cellar/dart"
        key: ${{ runner.os }}-homebrew-${{ vars.FVM_VERSION }}

    - name: Flutter Cache
      uses: actions/cache@v3
      if: runner.os == 'macOS'
      with:
        path: "/Users/runner/fvm/versions"
        key: ${{ runner.os }}-flutter

    - name: Homebrew Cache
      uses: actions/cache@v3
      if: runner.os == 'macOS'
      with:
        path: "/usr/local/Cellar/dart"
        key: ${{ runner.os }}-homebrew-${{ vars.FVM_VERSION }}

    - name: Setup fvm
      shell: bash
      run: |
        brew tap leoafarias/fvm
        brew install fvm$FVM_VERSION
        brew unlink dart

        fvm install
        fvm doctor

    - name: Setup global packages
      shell: bash
      run: |
        dart pub global activate melos
        dart pub global activate flutterfire_cli $FLUTTERFIRE_VERSION --overwrite
