name: Setup Flutter
description: Setup Flutter SDK

inputs:
  flutter_branch:
    description: Flutter branch
    required: false
    default: "beta"

runs:
  using: "composite"
  steps:
    - name: PATH
      shell: bash
      run: |
        echo "$HOME/fvm/versions/${{ inputs.flutter_branch }}/bin" >> $GITHUB_PATH
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

    - name: Setup Homebrew
      shell: bash
      if: runner.os == 'Linux'
      run: |
        # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#homebrew-note
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

    - name: Setup fvm
      shell: bash
      run: |
        brew tap leoafarias/fvm
        brew install fvm@3.0.0-beta.5
        fvm install ${{ inputs.flutter_branch }} --setup
        fvm doctor

    - name: Setup global packages
      shell: bash
      run: |
        dart pub global activate melos
        dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite
