name: Setup Flutter
description: Setup Flutter SDK

runs:
  using: "composite"
  steps:
    - name: PATH
      shell: bash
      run: |
        echo "$HOME/fvm/versions/beta/bin" >> $GITHUB_PATH
        echo "$HOME/fvm/versions/stable/bin" >> $GITHUB_PATH
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

    - name: Setup Homebrew
      shell: bash
      if: runner.os == 'Linux'
      run: |
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

    - name: Flutter Cache
      uses: actions/cache@v3
      if: runner.os == 'Linux'
      with:
        path: "/home/runner/fvm/versions"
        key: ${{ runner.os }}-flutter

    - name: Flutter Cache
      uses: actions/cache@v3
      if: runner.os == 'macOS'
      with:
        path: "/Users/runner/fvm/versions"
        key: ${{ runner.os }}-flutter

    - name: Setup fvm
      shell: bash
      run: |
        brew tap leoafarias/fvm
        brew install fvm@3.0.0-beta.5
        brew unlink dart

        fvm install
        fvm doctor

    - name: Setup global packages
      shell: bash
      run: |
        dart pub global activate melos
        dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite
