name: Setup Flutter
description: Setup Flutter SDK

inputs:
  flutter_branch:
    description: Flutter branch
    required: false
    default: "beta"

runs:
  using: "composite"
  steps:
    - name: Flutter action
      uses: subosito/flutter-action@v2.12.0
      with:
        channel: ${{ inputs.flutter_branch }}

    - name: PATH
      shell: bash
      run: |
        echo "$HOME/fvm/versions/${{ inputs.flutter_branch }}/bin" >> $GITHUB_PATH
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

    - name: Setup global packages
      shell: bash
      run: |
        dart pub global activate melos
        dart pub global activate fvm: 3.0.0-beta.5 --overwrite
        dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite

    - name: fvm
      shell: bash
      run: fvm doctor
