name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # - uses: KoheiKanagu/composite-actions/run-actionlint@main
      - uses: KoheiKanagu/composite-actions/setup-flutter@main

      - run: fvm flutter doctor -v
