name: Test

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-pull_request
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - uses: KoheiKanagu/composite-actions/run-actionlint@main
      - uses: KoheiKanagu/composite-actions/setup-flutter@cache

      - run: fvm flutter doctor -v

      - run: flutter --version
      - run: dart --version

  test_macOS:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      # - uses: KoheiKanagu/composite-actions/run-actionlint@main
      - uses: KoheiKanagu/composite-actions/setup-flutter@cache
        with:
          cache: 'false'

      - run: fvm flutter doctor -v

      - run: flutter --version
      - run: dart --version
