name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - uses: KoheiKanagu/composite-actions/run-actionlint@main
      - uses: KoheiKanagu/composite-actions/setup-flutter@main

      - run: fvm flutter doctor -v

      - run: flutter --version
      - run: dart --version

  test_macOS:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      # - uses: KoheiKanagu/composite-actions/run-actionlint@main
      - uses: KoheiKanagu/composite-actions/setup-flutter@main

      - run: fvm flutter doctor -v

      - run: flutter --version
      - run: dart --version
